import type { OpenClawPluginApi } from 'openclaw/plugin-sdk/core';
import { CHANNEL_ID } from '../constants.ts';
import { resolveXbotChannelPolicy } from '../policy.ts';
import {
  dispatchOpenClawReplyWithBufferedBlockDispatcher,
  formatOpenClawAgentEnvelope,
  recordXbotInboundSession,
  resolveOpenClawAgentRoute,
  resolveOpenClawEnvelopeFormatOptions,
  resolveXbotChannelInboundRuntime,
  resolveXbotInboundSessionStorePath,
  type OpenClawChannelRuntimeContext,
} from '../openclaw/runtime.ts';
import { buildXbotReplyConfig } from './reply-config.ts';
import {
  buildXbotAgentBodyWithHistory,
  buildXbotGroupHistoryKey,
  clearXbotPendingGroupHistory,
  formatXbotSpeakerLabel,
  readXbotPendingGroupHistorySnapshot,
  recordXbotPendingGroupText,
  type XbotGroupHistoryMap,
  type XbotHistoryEntry,
} from './group-history.ts';
import { decideXbotInboundTurn } from './turn-decision.ts';
import { mapOpenClawPayloadToReplies } from '../outbound/map-reply.ts';
import { resolveOutboundReceiver } from '../targets.ts';
import type { ParsedXbotInbound, XbotChannelConfigRoot, XbotReplyTarget } from '../types.ts';
import { sendViaXchatbotIfConfigured } from '../xchatbot-outbound.ts';

export type XbotDeliverContext = {
  cfg: XbotChannelConfigRoot;
  wechatApiBaseUrl: string;
  replyTarget: XbotReplyTarget;
  allocateReplyIndex?: () => number;
  onWarn?: (message: string) => void;
};

export type XbotDispatchResult = {
  dispatched: boolean;
  accumulated?: boolean;
  sessionKey?: string;
  reason?: string;
};

const HISTORY_FLUSH_SENDER_ID = 'xbot-history-system';
const HISTORY_FLUSH_SENDER_NAME = 'Xbot History System';
const HISTORY_FLUSH_RAW_BODY =
  'This message was automatically generated by the system for group context accumulation. Do not reply to the user. Output exactly NO_REPLY.';

export async function deliverXbotReply(
  deliverCtx: XbotDeliverContext,
  payload: {
    text?: string;
    mediaUrl?: string;
    mediaUrls?: string[];
    audioAsVoice?: boolean;
    asVoice?: boolean;
    mimeType?: string;
    fileName?: string;
    type?: string;
    kind?: string;
  },
  _info?: { kind?: 'tool' | 'block' | 'final' },
): Promise<void> {
  const outboundReplies = mapOpenClawPayloadToReplies(payload);
  if (outboundReplies.length === 0) return;

  const relayedByXchatbot = await sendViaXchatbotIfConfigured({
    cfg: deliverCtx.cfg,
    replyTarget: deliverCtx.replyTarget,
    replies: outboundReplies,
    onWarn: deliverCtx.onWarn,
  });
  if (!relayedByXchatbot) {
    throw new Error('xchatbot outbound relay is not configured or failed');
  }
}

export async function dispatchXbotInbound(args: {
  api: OpenClawPluginApi;
  cfg: XbotChannelConfigRoot;
  parsed: ParsedXbotInbound;
  wechatApiBaseUrl: string;
  groupHistories: XbotGroupHistoryMap;
  onIgnored?: (reason: string) => void;
  resolvedRouteOverride?: {
    sessionKey?: string;
    mainSessionKey?: string;
    agentId?: string;
  };
}): Promise<XbotDispatchResult> {
  const { api, cfg, parsed, wechatApiBaseUrl, groupHistories } = args;
  const channelCfg = cfg?.channels?.[CHANNEL_ID] || {};
  const policy = resolveXbotChannelPolicy(channelCfg);
  const turn = decideXbotInboundTurn({ policy, channelCfg, parsed });

  if (!turn.accept) {
    args.onIgnored?.(turn.reason || 'ignored');
    return { dispatched: false, reason: turn.reason };
  }

  const resolvedRoute = args.resolvedRouteOverride || resolveOpenClawAgentRoute(api, {
    cfg,
    channel: CHANNEL_ID,
    accountId: parsed.accountId,
    peer: parsed.peer,
  });
  const agentId = String(resolvedRoute.agentId || 'main').trim() || 'main';
  const sessionKey = String(resolvedRoute.sessionKey || '').trim();
  if (!sessionKey) {
    throw new Error('resolved sessionKey is empty');
  }

  let shouldDispatch = turn.shouldDispatch;
  let silentHistoryFlush = false;
  let pendingHistoryEntries: XbotHistoryEntry[] = [];

  // mention 模式：未点名先攒；窗满且 historyForce 时静默 flush 进 session
  if (!shouldDispatch && turn.shouldAccumulate) {
    recordXbotPendingGroupText({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });

    const historyKey = buildXbotGroupHistoryKey(parsed);
    const entries = historyKey ? groupHistories.get(historyKey) : undefined;
    const overflow =
      Boolean(historyKey)
      && turn.historyLimit > 0
      && Array.isArray(entries)
      && entries.length >= turn.historyLimit;

    if (overflow && turn.historyForce) {
      pendingHistoryEntries = readXbotPendingGroupHistorySnapshot({
        historyMap: groupHistories,
        parsed,
        historyLimit: turn.historyLimit,
      });
      shouldDispatch = true;
      silentHistoryFlush = true;
      api.logger?.info?.(
        `[xbot] group history force flush sessionKey=${sessionKey} entries=${pendingHistoryEntries.length}`,
      );
    } else {
      return {
        dispatched: false,
        accumulated: true,
        sessionKey,
        reason: 'history-accumulated',
      };
    }
  }

  if (shouldDispatch && !silentHistoryFlush && parsed.peer.kind === 'group') {
    pendingHistoryEntries = readXbotPendingGroupHistorySnapshot({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });
    if (pendingHistoryEntries.length > 0) {
      clearXbotPendingGroupHistory({
        historyMap: groupHistories,
        parsed,
        historyLimit: turn.historyLimit,
      });
    }
  }

  const storePath = resolveXbotInboundSessionStorePath({
    storeConfig: undefined,
    agentId,
  });
  const canonicalTo = resolveOutboundReceiver(parsed.route);
  const envelopeOptions = resolveOpenClawEnvelopeFormatOptions(api, cfg);

  const effectiveSenderId = silentHistoryFlush ? HISTORY_FLUSH_SENDER_ID : parsed.senderId;
  const effectiveSenderName = silentHistoryFlush
    ? HISTORY_FLUSH_SENDER_NAME
    : parsed.senderName;
  const effectiveRawBody = silentHistoryFlush ? HISTORY_FLUSH_RAW_BODY : parsed.rawBody;
  let outboundReplyIndex = 0;

  const agentVisibleBody = silentHistoryFlush
    ? buildXbotAgentBodyWithHistory({
        entries: pendingHistoryEntries,
        currentSenderName: HISTORY_FLUSH_SENDER_NAME,
        currentSenderId: HISTORY_FLUSH_SENDER_ID,
        currentBody: HISTORY_FLUSH_RAW_BODY,
      })
    : parsed.peer.kind === 'group'
      ? buildXbotAgentBodyWithHistory({
          entries: pendingHistoryEntries,
          currentSenderName: parsed.senderName,
          currentSenderId: parsed.senderId,
          currentBody: parsed.rawBody,
        })
      : parsed.rawBody;

  const envelopeFrom = silentHistoryFlush
    ? HISTORY_FLUSH_SENDER_NAME
    : parsed.peer.kind === 'group'
      ? formatXbotSpeakerLabel(parsed.senderName, parsed.senderId)
      : canonicalTo;

  const body = formatOpenClawAgentEnvelope(api, {
    channel: 'Xbot',
    from: envelopeFrom || canonicalTo,
    timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
    envelope: envelopeOptions,
    body: agentVisibleBody,
  });

  const inboundMediaUrl = silentHistoryFlush ? '' : String(parsed.mediaUrl || '').trim();
  const inboundMediaKind = silentHistoryFlush
    ? 'image'
    : (parsed.mediaKind === 'video' || parsed.mediaKind === 'emoji' || parsed.mediaKind === 'image'
      ? parsed.mediaKind
      : 'image');
  const inboundMedia = inboundMediaUrl
    ? [{
        path: inboundMediaUrl,
        url: inboundMediaUrl,
        contentType: inboundMediaKind === 'video'
          ? 'video/mp4'
          : inboundMediaKind === 'emoji'
            ? 'image/gif'
            : 'image/jpeg',
        kind: (inboundMediaKind === 'video' ? 'video' : 'image') as 'image' | 'video',
        messageId: parsed.messageId,
      }]
    : undefined;

  const inboundRuntime = resolveXbotChannelInboundRuntime(api);
  const ctxPayload = (await inboundRuntime.buildContext({
    channel: CHANNEL_ID,
    provider: CHANNEL_ID,
    surface: CHANNEL_ID,
    accountId: parsed.accountId,
    messageId: parsed.messageId,
    timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
    from: effectiveSenderId,
    sender: {
      id: effectiveSenderId,
      name: effectiveSenderName,
      username: effectiveSenderName,
    },
    conversation: {
      kind: parsed.peer.kind,
      id: parsed.peer.id,
      label: canonicalTo,
      routePeer: {
        kind: parsed.peer.kind,
        id: parsed.peer.id,
      },
    },
    route: {
      agentId,
      accountId: parsed.accountId,
      routeSessionKey: sessionKey,
      dispatchSessionKey: sessionKey,
      mainSessionKey: resolvedRoute.mainSessionKey,
    },
    reply: {
      to: canonicalTo,
      originatingTo: canonicalTo,
      replyToId: parsed.messageId,
    },
    message: {
      inboundEventKind: 'user_request',
      body,
      rawBody: effectiveRawBody,
      bodyForAgent: agentVisibleBody,
      commandBody: effectiveRawBody,
    },
    ...(inboundMedia ? { media: inboundMedia } : {}),
    access: {
      mentions: {
        canDetectMention: true,
        wasMentioned: silentHistoryFlush ? false : parsed.botMentioned,
        effectiveWasMentioned: silentHistoryFlush ? false : parsed.botMentioned,
      },
    },
    extra: {
      OriginatingChannel: CHANNEL_ID,
      OriginatingTo: canonicalTo,
      ...(silentHistoryFlush ? { historyFlush: true } : {}),
    },
  })) as OpenClawChannelRuntimeContext;

  const replyTarget: XbotReplyTarget = {
    accountId: parsed.accountId,
    to: canonicalTo,
    route: parsed.route,
    replyToMessageId: parsed.messageId,
    xchatbotApiBaseUrl: parsed.xchatbotApiBaseUrl,
    xchatbotAdminToken: parsed.xchatbotAdminToken,
  };

  const effectiveReply = buildXbotReplyConfig(cfg);

  const runResult = (await inboundRuntime.run({
    channel: CHANNEL_ID,
    accountId: parsed.accountId,
    raw: parsed,
    adapter: {
      ingest: () => ({
        id: parsed.messageId,
        timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
        rawText: effectiveRawBody,
        textForAgent: ctxPayload.BodyForAgent,
        textForCommands: ctxPayload.CommandBody,
        raw: parsed,
      }),
      resolveTurn: () => ({
        channel: CHANNEL_ID,
        accountId: parsed.accountId,
        agentId,
        routeSessionKey: sessionKey,
        storePath,
        ctxPayload,
        recordInboundSession: recordXbotInboundSession,
        record: {
          updateLastRoute: {
            channel: CHANNEL_ID,
            to: canonicalTo,
            accountId: parsed.accountId,
            sessionKey,
          },
          onRecordError: (err: unknown) => {
            args.api.logger?.warn?.(
              `[xbot] inbound record session failed: ${err instanceof Error ? err.message : String(err)}`,
            );
          },
        },
        runDispatch: async () =>
          dispatchOpenClawReplyWithBufferedBlockDispatcher(api, {
            ctx: ctxPayload,
            cfg: effectiveReply.replyCfg,
            dispatcherOptions: {
              deliver: async (payload, info) => {
                // 静默 flush：绝不往微信发
                if (silentHistoryFlush) return;

                const kind = info?.kind;
                const shouldForwardTool =
                  effectiveReply.blockStreaming && effectiveReply.allowTool;

                if (kind === 'tool' && !shouldForwardTool) {
                  return;
                }

                await deliverXbotReply({
                  cfg,
                  wechatApiBaseUrl,
                  replyTarget,
                  allocateReplyIndex: () => outboundReplyIndex++,
                  onWarn: (message: string) => {
                    args.api.logger?.warn?.(message);
                  },
                }, payload, info);
              },
              onError: (err: unknown) => {
                args.api.logger?.error?.(
                  `[xbot] outbound reply failed: ${err instanceof Error ? err.message : String(err)}`,
                );
              },
            },
            replyOptions: {
              disableBlockStreaming: !effectiveReply.blockStreaming,
              shouldEmitToolResult: effectiveReply.allowTool ? () => true : undefined,
            },
          }),
      }),
    },
  })) as {
    dispatched?: boolean;
    admission?: { kind?: string; reason?: string };
    dispatchResult?: {
      counts?: { tool?: number; block?: number; final?: number };
      observedReplyDelivery?: boolean;
      queuedFinal?: boolean;
    };
  } | undefined;

  if (shouldDispatch && parsed.peer.kind === 'group') {
    clearXbotPendingGroupHistory({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });
  }

  if (silentHistoryFlush) {
    return {
      dispatched: false,
      accumulated: true,
      sessionKey,
      reason: 'history-flush',
    };
  }

  const agentDispatched = runResult?.dispatched === true;
  const dispatchResult = runResult?.dispatchResult;
  const counts = dispatchResult?.counts;
  const hasVisibleReply =
    dispatchResult?.observedReplyDelivery === true
    || dispatchResult?.queuedFinal === true
    || (counts?.tool ?? 0) > 0
    || (counts?.block ?? 0) > 0
    || (counts?.final ?? 0) > 0;
  const dispatched = agentDispatched && hasVisibleReply;
  const admissionReason = runResult?.admission?.reason;
  return {
    dispatched,
    sessionKey,
    reason: dispatched
      ? undefined
      : !agentDispatched
        ? admissionReason || runResult?.admission?.kind || 'not-dispatched'
        : 'agent-no-reply',
  };
}
