import type { OpenClawPluginApi } from 'openclaw/plugin-sdk/core';
import { CHANNEL_ID } from '../constants.ts';
import { resolveXbotChannelPolicy } from '../policy.ts';
import {
  dispatchOpenClawReplyWithBufferedBlockDispatcher,
  formatOpenClawAgentEnvelope,
  recordXbotInboundSession,
  resolveOpenClawAgentRoute,
  resolveOpenClawEnvelopeFormatOptions,
  resolveXbotChannelInboundRuntime,
  resolveXbotInboundSessionStorePath,
  type OpenClawChannelRuntimeContext,
} from '../openclaw/runtime.ts';
import { buildXbotReplyConfig } from './reply-config.ts';
import {
  buildXbotAgentBodyWithHistory,
  buildXbotGroupHistoryKey,
  clearXbotPendingGroupHistory,
  formatXbotSpeakerLabel,
  readXbotPendingGroupHistorySnapshot,
  recordXbotPendingGroupText,
  type XbotGroupHistoryMap,
  type XbotHistoryEntry,
} from './group-history.ts';
import { decideXbotInboundTurn } from './turn-decision.ts';
import { loadInjectedChatContextBody } from './chat-context.ts';
import { formatOutboundFailure } from '../outbound/delivery.ts';
import { mapOpenClawPayloadToReplies } from '../outbound/map-reply.ts';
import { sendRepliesPipeline } from '../outbound/send-pipeline.ts';
import {
  filterRepliesAfterVoiceSent,
  shouldHoldVoiceFailureNarrative,
  wasVoiceRecentlySent,
} from '../outbound/voice-narrative-guard.ts';
import { resolveOutboundReceiver } from '../targets.ts';
import type { ParsedXbotInbound, XbotChannelConfigRoot, XbotReplyTarget } from '../types.ts';

export type XbotDeliverContext = {
  cfg: XbotChannelConfigRoot;
  wechatApiBaseUrl: string;
  replyTarget: XbotReplyTarget;
  allocateReplyIndex?: () => number;
  onWarn?: (message: string) => void;
  /** 本轮入站回复内是否已成功发出过语音（可变，跨多次 deliver 共享）。 */
  voiceSentThisTurn?: { value: boolean };
  /** 本轮是否已有媒体真实送达（含图片/视频/语音）。 */
  mediaSentThisTurn?: { value: boolean };
};

export type XbotDispatchResult = {
  dispatched: boolean;
  accumulated?: boolean;
  sessionKey?: string;
  reason?: string;
};

const HISTORY_FLUSH_SENDER_ID = 'xbot-history-system';
const HISTORY_FLUSH_SENDER_NAME = 'Xbot History System';
const HISTORY_FLUSH_RAW_BODY =
  'This message was automatically generated by the system for group context accumulation. Do not reply to the user. Output exactly NO_REPLY.';

/** 随机冒泡：未点名但系统已允许接话，避免 SOUL「没点名别开口」导致 NO_REPLY */
const AMBIENT_BUBBLE_HINT = [
  '[系统提示：群聊随机接话]',
  '用户没有点名你，但系统已允许你回一句。',
  '请用 1～2 句自然接话，像群友随口接茬；不要输出 NO_REPLY，不要解释系统机制，不要说自己是随机触发的。',
  '[/系统提示]',
].join('\n');

/** 接单后主动学习：别等用户喊「记一下」 */
function buildLearnScanHint(roomId: string): string {
  const roomLine = roomId
    ? `本群 roomId=${roomId}，写入 routes 时群字段尽量填它。`
    : '写入 routes 时群字段尽量填真实 roomId，没有再写 unknown。';
  return [
    '[系统提示：接单后先扫历史学习]',
    '先扫本次上下文近期消息，有可复用线索就立刻调用 xbot_learn_write，再回答用户；不要等对方说「记一下」。',
    '重点（放宽记）：指令/口令；@某人且对方有回应；有人认真回答了某类问题（可记以后问 TA，不只 @bot）。',
    '写 routes 必填 evidence；填 delegateTo 具体昵称；口令用 action；禁止目标写「见口令模板」。',
    roomLine,
    '[/系统提示]',
  ].join('\n');
}

export async function deliverXbotReply(
  deliverCtx: XbotDeliverContext,
  payload: {
    text?: string;
    mediaUrl?: string;
    mediaUrls?: string[];
    audioAsVoice?: boolean;
    asVoice?: boolean;
    mimeType?: string;
    fileName?: string;
    type?: string;
    kind?: string;
  },
  info?: { kind?: 'tool' | 'block' | 'final' },
): Promise<void> {
  // 注意：不能在 block 阶段丢掉 mediaUrl。
  // OpenClaw 常把语音只挂在 block/tool 上，final 只剩「发过去了」文字；丢掉媒体会导致微信完全看不到语音。
  // 重复投递靠 send-dedupe（同媒体 45s 内只发一次；文字仍可发）。
  const voiceSentFlag = deliverCtx.voiceSentThisTurn || { value: false };
  const mediaSentFlag = deliverCtx.mediaSentThisTurn || { value: false };
  deliverCtx.voiceSentThisTurn = voiceSentFlag;
  deliverCtx.mediaSentThisTurn = mediaSentFlag;
  const to = deliverCtx.replyTarget.route.groupId
    || deliverCtx.replyTarget.route.userId
    || deliverCtx.replyTarget.to;
  if (wasVoiceRecentlySent(to)) {
    voiceSentFlag.value = true;
    mediaSentFlag.value = true;
  }

  let outboundReplies = mapOpenClawPayloadToReplies(payload);
  if (outboundReplies.length === 0) return;

  // 同批已带语音时，直接丢掉失败定论文本（别和语音气泡一起出去打架）。
  if (outboundReplies.some((item) => item.type === 'voice')) {
    const filtered = filterRepliesAfterVoiceSent(outboundReplies);
    if (filtered.dropped > 0) {
      deliverCtx.onWarn?.(
        `[xbot] drop ${filtered.dropped} voice-failure text packed with voice media`,
      );
    }
    outboundReplies = filtered.replies;
    if (outboundReplies.length === 0) return;
  }

  // 本轮/近期已发出语音后：丢掉「做不了 / 没发出去」定论，避免成功后又补一句失败。
  if (voiceSentFlag.value) {
    const filtered = filterRepliesAfterVoiceSent(outboundReplies);
    if (filtered.dropped > 0) {
      deliverCtx.onWarn?.(
        `[xbot] drop ${filtered.dropped} stale voice-failure text after voice already sent`,
      );
    }
    outboundReplies = filtered.replies;
    if (outboundReplies.length === 0) return;
  } else {
    // 语音尚未成功：失败定论先扣住；仅 final 且整轮仍失败时才放行。
    const held: typeof outboundReplies = [];
    const kept: typeof outboundReplies = [];
    for (const reply of outboundReplies) {
      if (
        reply.type === 'text'
        && shouldHoldVoiceFailureNarrative({
          kind: info?.kind,
          voiceSentThisTurn: false,
          text: reply.content || '',
          allowFinalFailureNarrative: info?.kind === 'final',
        })
      ) {
        held.push(reply);
        continue;
      }
      kept.push(reply);
    }
    if (held.length > 0) {
      deliverCtx.onWarn?.(
        `[xbot] hold ${held.length} voice-failure text until media outcome is settled`,
      );
    }
    outboundReplies = kept;
    if (outboundReplies.length === 0) return;
  }

  const outbound = await sendRepliesPipeline({
    cfg: deliverCtx.cfg,
    accountId: deliverCtx.replyTarget.accountId,
    route: deliverCtx.replyTarget.route,
    replyTarget: deliverCtx.replyTarget,
    replies: outboundReplies,
    wechatApiBaseUrl: deliverCtx.wechatApiBaseUrl,
    onWarn: deliverCtx.onWarn,
  });

  if (outbound.voiceSent) voiceSentFlag.value = true;
  if (outbound.mediaSent || outbound.voiceSent) mediaSentFlag.value = true;

  // 部分成功：媒体到了就别整轮抛错（用户已看到气泡）；纯失败 / queued 才抛
  if (outbound.stage === 'wechat-ok' || outbound.stage === 'deduped') return;
  if (outbound.stage === 'partial' && (outbound.mediaSent || outbound.voiceSent)) {
    deliverCtx.onWarn?.(
      `[xbot] outbound partial but media delivered: ${formatOutboundFailure(outbound)}`,
    );
    return;
  }
  if (outbound.stage === 'queued') {
    deliverCtx.onWarn?.(
      `[xbot] outbound queued for retry: ${formatOutboundFailure(outbound)}`,
    );
  }
  throw new Error(formatOutboundFailure(outbound));
}

export async function dispatchXbotInbound(args: {
  api: OpenClawPluginApi;
  cfg: XbotChannelConfigRoot;
  parsed: ParsedXbotInbound;
  wechatApiBaseUrl: string;
  groupHistories: XbotGroupHistoryMap;
  onIgnored?: (reason: string) => void;
  resolvedRouteOverride?: {
    sessionKey?: string;
    mainSessionKey?: string;
    agentId?: string;
  };
}): Promise<XbotDispatchResult> {
  const { api, cfg, parsed, wechatApiBaseUrl, groupHistories } = args;
  const channelCfg = cfg?.channels?.[CHANNEL_ID] || {};
  const policy = resolveXbotChannelPolicy(channelCfg);
  const turn = decideXbotInboundTurn({ policy, channelCfg, parsed });

  if (!turn.accept) {
    args.onIgnored?.(turn.reason || 'ignored');
    return { dispatched: false, reason: turn.reason };
  }

  const resolvedRoute = args.resolvedRouteOverride || resolveOpenClawAgentRoute(api, {
    cfg,
    channel: CHANNEL_ID,
    accountId: parsed.accountId,
    peer: parsed.peer,
  });
  const agentId = String(resolvedRoute.agentId || 'main').trim() || 'main';
  const sessionKey = String(resolvedRoute.sessionKey || '').trim();
  if (!sessionKey) {
    throw new Error('resolved sessionKey is empty');
  }

  let shouldDispatch = turn.shouldDispatch;
  let silentHistoryFlush = false;
  let pendingHistoryEntries: XbotHistoryEntry[] = [];

  // mention 模式：未点名先攒；窗满且 historyForce 时静默 flush 进 session
  if (!shouldDispatch && turn.shouldAccumulate) {
    recordXbotPendingGroupText({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });

    const historyKey = buildXbotGroupHistoryKey(parsed);
    const entries = historyKey ? groupHistories.get(historyKey) : undefined;
    const overflow =
      Boolean(historyKey)
      && turn.historyLimit > 0
      && Array.isArray(entries)
      && entries.length >= turn.historyLimit;

    if (overflow && turn.historyForce) {
      pendingHistoryEntries = readXbotPendingGroupHistorySnapshot({
        historyMap: groupHistories,
        parsed,
        historyLimit: turn.historyLimit,
      });
      shouldDispatch = true;
      silentHistoryFlush = true;
      api.logger?.info?.(
        `[xbot] group history force flush sessionKey=${sessionKey} entries=${pendingHistoryEntries.length}`,
      );
    } else {
      return {
        dispatched: false,
        accumulated: true,
        sessionKey,
        reason: 'history-accumulated',
      };
    }
  }

  if (shouldDispatch && !silentHistoryFlush && parsed.peer.kind === 'group') {
    pendingHistoryEntries = readXbotPendingGroupHistorySnapshot({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });
    if (pendingHistoryEntries.length > 0) {
      clearXbotPendingGroupHistory({
        historyMap: groupHistories,
        parsed,
        historyLimit: turn.historyLimit,
      });
    }
  }

  const storePath = resolveXbotInboundSessionStorePath({
    storeConfig: undefined,
    agentId,
  });
  const canonicalTo = resolveOutboundReceiver(parsed.route);
  const envelopeOptions = resolveOpenClawEnvelopeFormatOptions(api, cfg);

  const effectiveSenderId = silentHistoryFlush ? HISTORY_FLUSH_SENDER_ID : parsed.senderId;
  const effectiveSenderName = silentHistoryFlush
    ? HISTORY_FLUSH_SENDER_NAME
    : parsed.senderName;
  const effectiveRawBody = silentHistoryFlush ? HISTORY_FLUSH_RAW_BODY : parsed.rawBody;
  let outboundReplyIndex = 0;

  let agentVisibleBody: string;
  if (silentHistoryFlush) {
    agentVisibleBody = buildXbotAgentBodyWithHistory({
      entries: pendingHistoryEntries,
      currentSenderName: HISTORY_FLUSH_SENDER_NAME,
      currentSenderId: HISTORY_FLUSH_SENDER_ID,
      currentBody: HISTORY_FLUSH_RAW_BODY,
    });
  } else {
    const injectedBody = await loadInjectedChatContextBody({
      cfg,
      channelCfg: channelCfg as Record<string, unknown>,
      parsed,
      onWarn: (message) => {
        api.logger?.warn?.(message);
      },
    });
    if (injectedBody) {
      // D1 近期上下文已覆盖 pending，避免重复堆叠
      agentVisibleBody = injectedBody;
    } else if (parsed.peer.kind === 'group') {
      agentVisibleBody = buildXbotAgentBodyWithHistory({
        entries: pendingHistoryEntries,
        currentSenderName: parsed.senderName,
        currentSenderId: parsed.senderId,
        currentBody: parsed.rawBody,
      });
    } else {
      agentVisibleBody = parsed.rawBody;
    }
    if (parsed.peer.kind === 'group') {
      const roomId = String(parsed.peer.id || '').trim();
      agentVisibleBody = `${buildLearnScanHint(roomId)}\n\n${agentVisibleBody}`;
    }
    if (parsed.forceDispatch === true) {
      agentVisibleBody = `${AMBIENT_BUBBLE_HINT}\n\n${agentVisibleBody}`;
    }
  }

  const envelopeFrom = silentHistoryFlush
    ? HISTORY_FLUSH_SENDER_NAME
    : parsed.peer.kind === 'group'
      ? formatXbotSpeakerLabel(parsed.senderName, parsed.senderId)
      : canonicalTo;

  const body = formatOpenClawAgentEnvelope(api, {
    channel: 'Xbot',
    from: envelopeFrom || canonicalTo,
    timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
    envelope: envelopeOptions,
    body: agentVisibleBody,
  });

  const inboundMediaUrl = silentHistoryFlush ? '' : String(parsed.mediaUrl || '').trim();
  const inboundMediaKind = silentHistoryFlush
    ? 'image'
    : (parsed.mediaKind === 'video'
      || parsed.mediaKind === 'emoji'
      || parsed.mediaKind === 'image'
      || parsed.mediaKind === 'voice'
      || parsed.mediaKind === 'audio'
      ? parsed.mediaKind
      : 'image');
  const inboundMedia = inboundMediaUrl
    ? [{
        path: inboundMediaUrl,
        url: inboundMediaUrl,
        contentType: inboundMediaKind === 'video'
          ? 'video/mp4'
          : inboundMediaKind === 'emoji'
            ? 'image/gif'
            : (inboundMediaKind === 'voice' || inboundMediaKind === 'audio')
              ? 'audio/silk'
              : 'image/jpeg',
        kind: (inboundMediaKind === 'video'
          ? 'video'
          : (inboundMediaKind === 'voice' || inboundMediaKind === 'audio')
            ? 'audio'
            : 'image') as 'image' | 'video' | 'audio',
        messageId: parsed.messageId,
      }]
    : undefined;

  const inboundRuntime = resolveXbotChannelInboundRuntime(api);
  const ctxPayload = (await inboundRuntime.buildContext({
    channel: CHANNEL_ID,
    provider: CHANNEL_ID,
    surface: CHANNEL_ID,
    accountId: parsed.accountId,
    messageId: parsed.messageId,
    timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
    from: effectiveSenderId,
    sender: {
      id: effectiveSenderId,
      name: effectiveSenderName,
      username: effectiveSenderName,
    },
    conversation: {
      kind: parsed.peer.kind,
      id: parsed.peer.id,
      label: canonicalTo,
      routePeer: {
        kind: parsed.peer.kind,
        id: parsed.peer.id,
      },
    },
    route: {
      agentId,
      accountId: parsed.accountId,
      routeSessionKey: sessionKey,
      dispatchSessionKey: sessionKey,
      mainSessionKey: resolvedRoute.mainSessionKey,
    },
    reply: {
      to: canonicalTo,
      originatingTo: canonicalTo,
      replyToId: parsed.messageId,
    },
    message: {
      inboundEventKind: 'user_request',
      body,
      rawBody: effectiveRawBody,
      bodyForAgent: agentVisibleBody,
      commandBody: effectiveRawBody,
    },
    ...(inboundMedia ? { media: inboundMedia } : {}),
    access: {
      mentions: {
        canDetectMention: true,
        // 冒泡 forceDispatch：按「已允许接话」处理，避免核心层因未点名静默
        wasMentioned: silentHistoryFlush
          ? false
          : parsed.botMentioned || parsed.forceDispatch === true,
        effectiveWasMentioned: silentHistoryFlush
          ? false
          : parsed.botMentioned || parsed.forceDispatch === true,
      },
    },
    extra: {
      OriginatingChannel: CHANNEL_ID,
      OriginatingTo: canonicalTo,
      ...(silentHistoryFlush ? { historyFlush: true } : {}),
      ...(parsed.forceDispatch === true ? { ambientBubble: true } : {}),
    },
  })) as OpenClawChannelRuntimeContext;

  const replyTarget: XbotReplyTarget = {
    accountId: parsed.accountId,
    to: canonicalTo,
    route: parsed.route,
    replyToMessageId: parsed.messageId,
    xchatbotApiBaseUrl: parsed.xchatbotApiBaseUrl,
    xchatbotAdminToken: parsed.xchatbotAdminToken,
  };

  const effectiveReply = buildXbotReplyConfig(cfg);

  const runResult = (await inboundRuntime.run({
    channel: CHANNEL_ID,
    accountId: parsed.accountId,
    raw: parsed,
    adapter: {
      ingest: () => ({
        id: parsed.messageId,
        timestamp: silentHistoryFlush ? Date.now() : parsed.timestamp,
        rawText: effectiveRawBody,
        textForAgent: ctxPayload.BodyForAgent,
        textForCommands: ctxPayload.CommandBody,
        raw: parsed,
      }),
      resolveTurn: () => ({
        channel: CHANNEL_ID,
        accountId: parsed.accountId,
        agentId,
        routeSessionKey: sessionKey,
        storePath,
        ctxPayload,
        recordInboundSession: recordXbotInboundSession,
        record: {
          updateLastRoute: {
            channel: CHANNEL_ID,
            to: canonicalTo,
            accountId: parsed.accountId,
            sessionKey,
          },
          onRecordError: (err: unknown) => {
            args.api.logger?.warn?.(
              `[xbot] inbound record session failed: ${err instanceof Error ? err.message : String(err)}`,
            );
          },
        },
        runDispatch: async () => {
          const voiceSentThisTurn = { value: false };
          const mediaSentThisTurn = { value: false };
          return dispatchOpenClawReplyWithBufferedBlockDispatcher(api, {
            ctx: ctxPayload,
            cfg: effectiveReply.replyCfg,
            dispatcherOptions: {
              deliver: async (payload, info) => {
                // 静默 flush：绝不往微信发
                if (silentHistoryFlush) return;

                const kind = info?.kind;
                const shouldForwardTool =
                  effectiveReply.blockStreaming && effectiveReply.allowTool;

                if (kind === 'tool' && !shouldForwardTool) {
                  return;
                }

                await deliverXbotReply({
                  cfg,
                  wechatApiBaseUrl,
                  replyTarget,
                  allocateReplyIndex: () => outboundReplyIndex++,
                  voiceSentThisTurn,
                  mediaSentThisTurn,
                  onWarn: (message: string) => {
                    args.api.logger?.warn?.(message);
                  },
                }, payload, info);
              },
              onError: (err: unknown) => {
                args.api.logger?.error?.(
                  `[xbot] outbound reply failed: ${err instanceof Error ? err.message : String(err)}`,
                );
              },
            },
            replyOptions: {
              disableBlockStreaming: !effectiveReply.blockStreaming,
              shouldEmitToolResult: effectiveReply.allowTool ? () => true : undefined,
            },
          });
        },
      }),
    },
  })) as {
    dispatched?: boolean;
    admission?: { kind?: string; reason?: string };
    dispatchResult?: {
      counts?: { tool?: number; block?: number; final?: number };
      observedReplyDelivery?: boolean;
      queuedFinal?: boolean;
    };
  } | undefined;

  if (shouldDispatch && parsed.peer.kind === 'group') {
    clearXbotPendingGroupHistory({
      historyMap: groupHistories,
      parsed,
      historyLimit: turn.historyLimit,
    });
  }

  if (silentHistoryFlush) {
    return {
      dispatched: false,
      accumulated: true,
      sessionKey,
      reason: 'history-flush',
    };
  }

  const agentDispatched = runResult?.dispatched === true;
  const dispatchResult = runResult?.dispatchResult;
  const counts = dispatchResult?.counts;
  const hasVisibleReply =
    dispatchResult?.observedReplyDelivery === true
    || dispatchResult?.queuedFinal === true
    || (counts?.tool ?? 0) > 0
    || (counts?.block ?? 0) > 0
    || (counts?.final ?? 0) > 0;
  // 冒泡 forceDispatch：Agent 已启动即算接手，避免「尚无可见回复」时 Worker 回落本地聪明对话
  const forceDispatch = parsed.forceDispatch === true;
  const dispatched = agentDispatched && (hasVisibleReply || forceDispatch);
  const admissionReason = runResult?.admission?.reason;
  return {
    dispatched,
    sessionKey,
    reason: dispatched
      ? (forceDispatch && !hasVisibleReply ? 'force-dispatch-accepted' : undefined)
      : !agentDispatched
        ? admissionReason || runResult?.admission?.kind || 'not-dispatched'
        : 'agent-no-reply',
  };
}
